/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelProject.ui;

import HotelProject.persistence.dao.FuncionarioDao;
import HotelProject.persistence.entities.Funcionario;
import HotelProject.utils.DateUtils.DateVerifier;
import HotelProject.utils.NumberUtils;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Jackson
 */
public class FuncionariosPanel extends javax.swing.JPanel {

    FuncionarioDao funcionarioDao = new FuncionarioDao();
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    MaskFormatter maskDate, phoneMask;
    Funcionario funcionario;
    NumberFormat numberFormat = NumberFormat.getNumberInstance();
    int editIndex = -1;
    /**
     * Creates new form Hospedes
     */
    public FuncionariosPanel() {
        try {
            maskDate = new MaskFormatter("##/##/####");
            maskDate.setPlaceholderCharacter('_');
            phoneMask = new MaskFormatter("(##) #####-####");
            phoneMask.setPlaceholderCharacter('_');
        } catch (ParseException e) {
        }
        initComponents();
        
        cadastroPanel.setVisible(false);
        listagemPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroPanel = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        nomeInput = new javax.swing.JTextField();
        enderecoInput = new javax.swing.JTextField();
        cidadeInput = new javax.swing.JTextField();
        estadoInput = new javax.swing.JTextField();
        telefoneInput = new javax.swing.JFormattedTextField(phoneMask);
        btnSave = new javax.swing.JButton();
        dataNascimentoInput = new javax.swing.JFormattedTextField(maskDate);
        salarioInput = new javax.swing.JFormattedTextField(numberFormat);
        listagemPanel = new javax.swing.JPanel();
        btnNovoFuncionario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployee = new javax.swing.JTable();
        btnDelFuncionario = new javax.swing.JButton();
        btnEditFuncionario = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(622, 363));
        setLayout(null);

        cadastroPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setIconTextGap(0);
        btnVoltar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnVoltar.setMinimumSize(new java.awt.Dimension(10, 10));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        nomeInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        enderecoInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        cidadeInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Cidade"));

        estadoInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        telefoneInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));

        btnSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jackson\\Desktop\\NetBeansProjects\\icons\\save_50px.png")); // NOI18N
        btnSave.setBorder(null);
        btnSave.setBorderPainted(false);
        btnSave.setIconTextGap(0);
        btnSave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        dataNascimentoInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Nascimento"));
        dataNascimentoInput.setInputVerifier(new DateVerifier());

        salarioInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Salário"));
        salarioInput.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                salarioInputPropertyChange(evt);
            }
        });
        salarioInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salarioInputKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salarioInputKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout cadastroPanelLayout = new javax.swing.GroupLayout(cadastroPanel);
        cadastroPanel.setLayout(cadastroPanelLayout);
        cadastroPanelLayout.setHorizontalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enderecoInput)
                    .addGroup(cadastroPanelLayout.createSequentialGroup()
                        .addComponent(cidadeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estadoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(cadastroPanelLayout.createSequentialGroup()
                        .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cadastroPanelLayout.createSequentialGroup()
                                .addComponent(nomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadastroPanelLayout.createSequentialGroup()
                                .addComponent(dataNascimentoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cadastroPanelLayout.setVerticalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );

        add(cadastroPanel);
        cadastroPanel.setBounds(0, 0, 622, 363);

        listagemPanel.setBackground(new java.awt.Color(255, 255, 255));
        listagemPanel.setForeground(new java.awt.Color(255, 255, 255));
        listagemPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listagemPanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnNovoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-user.png"))); // NOI18N
        btnNovoFuncionario.setBorder(null);
        btnNovoFuncionario.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFuncionarioActionPerformed(evt);
            }
        });

        tableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Endereço", "Cidade", "Estado", "Telefone", "Data Nasc.", "Salário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableEmployee);

        btnDelFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove-user.png"))); // NOI18N
        btnDelFuncionario.setBorder(null);
        btnDelFuncionario.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnDelFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelFuncionarioMouseClicked(evt);
            }
        });

        btnEditFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-user.png"))); // NOI18N
        btnEditFuncionario.setBorder(null);
        btnEditFuncionario.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnEditFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listagemPanelLayout = new javax.swing.GroupLayout(listagemPanel);
        listagemPanel.setLayout(listagemPanelLayout);
        listagemPanelLayout.setHorizontalGroup(
            listagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listagemPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovoFuncionario)))
                .addContainerGap())
        );
        listagemPanelLayout.setVerticalGroup(
            listagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listagemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoFuncionario)
                    .addComponent(btnDelFuncionario)
                    .addComponent(btnEditFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(listagemPanel);
        listagemPanel.setBounds(0, 0, 622, 363);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        resetFormEmployee();
        cadastroPanel.setVisible(false);
        listagemPanel.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        DefaultTableModel dataModel = (DefaultTableModel) tableEmployee.getModel();

        Boolean edit = funcionario != null;

        if (!edit) {
            funcionario = new Funcionario();
        }

        if (nomeInput.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o nome", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (salarioInput.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o salário", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        funcionario.setNome(nomeInput.getText());
        funcionario.setTelefone(telefoneInput.getText());
        funcionario.setEndereco(enderecoInput.getText());
        funcionario.setCidade(cidadeInput.getText());
        funcionario.setEstado(estadoInput.getText());
        funcionario.setDataNascimento(dataNascimentoInput.getText(), df);
        funcionario.setSalario(NumberUtils.getNumericValue(salarioInput.getText()));

        if (!edit) {
            funcionarioDao.save(funcionario);
            dataModel.addRow(getFuncionarioRow(funcionario));
        }
        else {
            funcionarioDao.update(funcionario);
            dataModel.removeRow(editIndex);
            dataModel.insertRow(editIndex, getFuncionarioRow(funcionario));
        }

        resetFormEmployee();

        cadastroPanel.setVisible(false);
        listagemPanel.setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void salarioInputPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_salarioInputPropertyChange

    }//GEN-LAST:event_salarioInputPropertyChange

    private void salarioInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salarioInputKeyPressed
        formatSalarioInput();
    }//GEN-LAST:event_salarioInputKeyPressed

    private void salarioInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salarioInputKeyTyped
        formatSalarioInput();
    }//GEN-LAST:event_salarioInputKeyTyped

    private void btnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFuncionarioActionPerformed
        resetFormEmployee();
        cadastroPanel.setVisible(true);
        listagemPanel.setVisible(false);
    }//GEN-LAST:event_btnNovoFuncionarioActionPerformed

    private void btnDelFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelFuncionarioMouseClicked
        DefaultTableModel dataModel = (DefaultTableModel) tableEmployee.getModel();

        int i = tableEmployee.getSelectedRow();
        if (i >= 0) {
            Integer id = Integer.parseInt(dataModel.getValueAt(i, 0).toString());
            Funcionario funcionario = funcionarioDao.find(id);

            int input = JOptionPane.showConfirmDialog(null, "Remover "+ funcionario.getNome()+ "?", "Remover funcionário",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (input == JOptionPane.YES_OPTION) {
                funcionarioDao.delete(funcionario);
                dataModel.removeRow(i);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione na tabela", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDelFuncionarioMouseClicked

    private void btnEditFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFuncionarioActionPerformed
        DefaultTableModel dataModel = (DefaultTableModel) tableEmployee.getModel();

        editIndex = tableEmployee.getSelectedRow();
        if (editIndex >= 0) {
            Integer id = Integer.parseInt(dataModel.getValueAt(editIndex, 0).toString());
            funcionario = funcionarioDao.find(id);

            nomeInput.setText(funcionario.getNome());
            telefoneInput.setText(funcionario.getTelefone());
            enderecoInput.setText(funcionario.getEndereco());
            cidadeInput.setText(funcionario.getCidade());
            estadoInput.setText(funcionario.getEstado());
            dataNascimentoInput.setText(formatDate(funcionario.getDataNascimento()));
            salarioInput.setText(formatNumber(funcionario.getSalario()));

            cadastroPanel.setVisible(true);
            listagemPanel.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione na tabela", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditFuncionarioActionPerformed

    private void listagemPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listagemPanelAncestorAdded
        fillEmployeeTable();
    }//GEN-LAST:event_listagemPanelAncestorAdded

    private void formatSalarioInput() {
        String str = salarioInput.getText();
        salarioInput.setText(NumberUtils.format(str));
    }
    
    private void resetFormEmployee() {
        nomeInput.setText("");
        salarioInput.setText("");
        enderecoInput.setText("");
        cidadeInput.setText("");
        estadoInput.setText("");
        dataNascimentoInput.setText("");
        salarioInput.setText("");
        telefoneInput.setText("");
        funcionario = null;
    }
    
    private void fillEmployeeTable() {
        DefaultTableModel dataModel = (DefaultTableModel) tableEmployee.getModel();
        
        if (dataModel.getRowCount() > 0) {
            return;
        }
        
        List<Funcionario> funcionarios = funcionarioDao.getAll();
        
        Iterator<Funcionario> funcionariosIterator = funcionarios.iterator();
        while (funcionariosIterator.hasNext()){
            Funcionario funcionario = (Funcionario) funcionariosIterator.next();
            dataModel.addRow(getFuncionarioRow(funcionario));
         }
         
        tableEmployee.setModel(dataModel);
    }
    
    private Object[] getFuncionarioRow(Funcionario funcionario) {
        return new Object[] {
            funcionario.getId(),
            funcionario.getNome(),
            funcionario.getEndereco(),
            funcionario.getCidade(),
            funcionario.getEstado(),
            funcionario.getTelefone(),
            formatDate(funcionario.getDataNascimento()),
            "R$ " + formatNumber(funcionario.getSalario())
        };
    }
    
    private String formatDate(Date date) {
        String dateStr =  "";
        try {
            dateStr = df.format(date);
        } catch(Exception ex) {
            //
        }
        return dateStr;
    }
    
    private String formatNumber(Double value) {
        String valueStr =  "0";
        try {
            valueStr = numberFormat.format(value);
        } catch(Exception ex) {
            //
        }
        return valueStr;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelFuncionario;
    private javax.swing.JButton btnEditFuncionario;
    private javax.swing.JButton btnNovoFuncionario;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel cadastroPanel;
    private javax.swing.JTextField cidadeInput;
    private javax.swing.JFormattedTextField dataNascimentoInput;
    private javax.swing.JTextField enderecoInput;
    private javax.swing.JTextField estadoInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listagemPanel;
    private javax.swing.JTextField nomeInput;
    private javax.swing.JFormattedTextField salarioInput;
    private javax.swing.JTable tableEmployee;
    private javax.swing.JTextField telefoneInput;
    // End of variables declaration//GEN-END:variables
}
