/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelProject;

import HotelProject.ui.CenterTabbedPane;
import mdlaf.*;
import mdlaf.animation.*;
import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Jackson
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public App() {
        initComponents();
//        tabs.setUI(new CenterTabbedPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        tabs = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        funcionariosPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNovoFuncionario = new javax.swing.JButton();
        hopedesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnNovoHospede = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Manager");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        desktopPane.setLayout(new java.awt.BorderLayout());

        tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabs.setAutoscrolls(true);
        tabs.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tabs.setMinimumSize(new java.awt.Dimension(250, 30));

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setAlignmentY(15.0F);
        homePanel.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("TELA INICIAL");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(153, 153, 153))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        tabs.addTab("Início", homePanel);

        funcionariosPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Jackson", null, "1200"},
                {"2", "Aline", null, "1500"},
                {"3", "Igor", null, "2000"},
                {"4", "Miguel", null, "3000"}
            },
            new String [] {
                "ID", "Nome", "Endereço", "Salário"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnNovoFuncionario.setText("NOVO");

        javax.swing.GroupLayout funcionariosPanelLayout = new javax.swing.GroupLayout(funcionariosPanel);
        funcionariosPanel.setLayout(funcionariosPanelLayout);
        funcionariosPanelLayout.setHorizontalGroup(
            funcionariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funcionariosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(funcionariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funcionariosPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovoFuncionario)))
                .addContainerGap())
        );
        funcionariosPanelLayout.setVerticalGroup(
            funcionariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funcionariosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        tabs.addTab("Funcionários", funcionariosPanel);

        hopedesPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Jackson", null, "1200"},
                {"2", "Aline", null, "1500"},
                {"3", "Igor", null, "2000"},
                {"4", "Miguel", null, "3000"}
            },
            new String [] {
                "ID", "Nome", "Endereço", "Salário"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnNovoHospede.setText("NOVO");

        javax.swing.GroupLayout hopedesPanelLayout = new javax.swing.GroupLayout(hopedesPanel);
        hopedesPanel.setLayout(hopedesPanelLayout);
        hopedesPanelLayout.setHorizontalGroup(
            hopedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hopedesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hopedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hopedesPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovoHospede)))
                .addContainerGap())
        );
        hopedesPanelLayout.setVerticalGroup(
            hopedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hopedesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoHospede)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        tabs.addTab("Hóspedes", hopedesPanel);

        desktopPane.add(tabs, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoFuncionario;
    private javax.swing.JButton btnNovoHospede;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel funcionariosPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel hopedesPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables

}
